### ISSUE TITLE
new release 1.0.7

### ISSUE THREAD

**Issue by cdenneen** [mvisonneau/puppet-curator#16]
@mvisonneau would you mind tagging new release to forge?

**Comment by mvisonneau** [comment]
Hmm indeed, that is weird it should be automated 🤔

**Comment by mvisonneau** [comment]
there was an error in the last release of the forge : https://travis-ci.org/mvisonneau/puppet-curator/jobs/415541230, looking into it and will then release `1.0.7`

**Comment by smortex** [comment]
Maybe fixed by #17 (since there where various issues, I fixed them and as a side effect, the job seems to be fixed :wink:).

**Comment by smortex** [comment]
Looks like `1.0.7` was tagged, but the resulting artifact is not published to the Puppet forge.  As far as I can see, the tag should be named `v1.0.7` in order to match the `/^v\d+/` regular expression that would trigger a build:

https://github.com/mvisonneau/puppet-curator/blob/37523bcf72c8e8b63ed59c5ff7a65047f4acdca6/.travis.yml#L27-L31

**Comment by mvisonneau** [comment]
🤦‍♂️ indeed 👍 just updated the tag, thanks @smortex

**Comment by mvisonneau** [comment]
new version has been properly released now 👍
